import { useRef } from 'react'
import { Check, FileText, Plus } from '@phosphor-icons/react'
import { Badge, Button, Input, PreviewIcon } from '../components/primitives'
import { STATUSES, type ClaimStatus, type RegistryClaim } from '../data/registry'
import { PIC_OPTIONS } from '../data/localState'
import { customerEmail, incidentDate, money, shortDate, stamp, type Assessment, type ClaimDocument, type WorkspaceState } from './model'

export function ClaimDetails({ claim, state }: { claim: RegistryClaim; state: WorkspaceState }) {
  const sections: [string, [string, string][]][] = [
    ['Overview', [['Claim number', claim.claimNo], ['Claim type', claim.claimType], ['Status', state.status], ['Category', state.category], ['Person in charge', state.pic], ['Source', 'Customer portal · local fixture']]],
    ['Claimant', [['Full name', claim.customer], ['Relationship', 'Policyholder & insured'], ['Email', customerEmail(claim)], ['Phone', `+60 12-000 ${claim.claimNo.slice(-4)} (demo)`], ['Country', 'Malaysia']]],
    ['Policy', [['Policy number', claim.policyNo], ['Product', 'TripCare 360 International'], ['Cover', 'Single trip · Asia Pacific'], ['Cover period', `${shortDate(incidentDate(claim))} – ${shortDate(new Date(new Date(incidentDate(claim)).getTime() + 14 * 86400000).toISOString())}`], ['Policy verification', state.tasks[0] ? 'Verified' : 'Pending review']]],
    ['Incident', [['Date of loss', shortDate(incidentDate(claim))], ['Journey', 'Kuala Lumpur → Bangkok'], ['Description', `Customer reported ${claim.claimType.toLowerCase()} during the insured journey. Review the attached evidence against the policy benefit.`]]],
    ['Financial', [['Currency', 'MYR'], ['Claimed', money(state.assessment.claimed)], ['Eligible (provisional)', money(state.assessment.eligible)], ['Deductible', money(state.assessment.deductible)], ['Net payable (provisional)', money(Number(state.assessment.eligible) - Number(state.assessment.deductible))], ['Recommendation', state.assessment.recommendation]]],
    ['Dates & metadata', [['Registered', stamp(claim.registeredAt)], ['Latest source activity', stamp(claim.activityAt)], ['SLA target', shortDate(claim.dueAt)], ['Follow-up', state.assessment.followUp ? shortDate(state.assessment.followUp) : 'Not scheduled'], ['Timezone', 'Malaysia · UTC+08:00'], ['Environment', 'Synthetic preview data']]],
  ]
  return <><div className="ws-centre-heading"><div><h2>Claim details</h2><p>The full claim record, for reference.</p></div><Badge>Read only</Badge></div><div className="ws-detail-sections">{sections.map(([title, fields]) => <section key={title}><h3>{title}</h3><dl>{fields.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section>)}</div></>
}

export function Documents({ state, preview, upload, verify }: { state: WorkspaceState; preview: (document: ClaimDocument) => void; upload: (files: FileList | null, replace?: string) => void; verify: (id: string) => void }) {
  const fileInput = useRef<HTMLInputElement>(null), replacing = useRef<string | undefined>(undefined)
  const required = state.documents.filter(document => ['policy', 'itinerary', 'evidence'].includes(document.id))
  const others = state.documents.filter(document => !['policy', 'itinerary', 'evidence'].includes(document.id))
  const render = (document: ClaimDocument) => <article className="ws-document-row" key={document.id}><span className="ws-document-icon"><PreviewIcon icon={FileText} size="navigation" /></span><div><strong>{document.kind}</strong><span>{document.status === 'Missing' ? 'Not received from customer' : document.name}</span><small>{document.source}{document.date && ` · ${shortDate(document.date)}`}</small><Badge tone={document.status === 'Missing' ? 'accent' : document.status === 'Verified' ? 'success' : 'neutral'}>{document.status}</Badge></div><div className="ws-document-buttons">{document.status !== 'Missing' ? <><Button onClick={() => preview(document)}>Preview</Button>{document.status === 'Received' && <Button variant="ghost" onClick={() => verify(document.id)}><PreviewIcon icon={Check} />Verify</Button>}</> : <Button onClick={() => { replacing.current = document.id; fileInput.current?.click() }}>Add file</Button>}</div></article>
  return <><div className="ws-centre-heading"><div><h2>Documents</h2><p>{state.documents.filter(document => document.status === 'Missing').length} missing · {state.documents.filter(document => document.status === 'Received').length} awaiting verification</p></div><Button onClick={() => { replacing.current = undefined; fileInput.current?.click() }}><PreviewIcon icon={Plus} />Add file</Button><input ref={fileInput} type="file" accept=".pdf,.png,.jpg,.jpeg,.txt" className="pv-sr-only" aria-label="Upload local document" onChange={event => { upload(event.target.files, replacing.current); event.target.value = '' }} /></div><div className="ws-document-list"><h3>Required documents</h3>{required.map(render)}{others.length > 0 && <><h3>Additional files</h3>{others.map(render)}</>}<p className="ws-local-caption">PDF, JPG, PNG, or TXT · up to 1 MB per file. Files stay in this browser tab.</p></div></>
}

export function AssessmentForm({ state, change, save, reset }: { state: WorkspaceState; change: (fields: Partial<Assessment>) => void; save: () => void; reset: () => void }) {
  const draft = state.assessmentDraft
  const dirty = JSON.stringify(draft) !== JSON.stringify(state.assessment)
  return <><div className="ws-centre-heading"><div><h2>Assessment</h2><p>Review coverage, set the outcome, and record your rationale.</p></div><Badge tone={dirty ? 'accent' : 'neutral'}>{dirty ? 'Unsaved changes' : 'Saved'}</Badge></div><form className="ws-assessment-form" onSubmit={event => { event.preventDefault(); save() }}>
    <fieldset><legend>Operational details</legend><div className="ws-form-grid"><label>Status<select aria-label="Status" value={draft.status} onChange={event => change({ status: event.target.value as ClaimStatus })}>{STATUSES.map(status => <option key={status}>{status}</option>)}</select></label><label>PIC<select aria-label="PIC" value={draft.pic} onChange={event => change({ pic: event.target.value })}>{PIC_OPTIONS.map(pic => <option key={pic}>{pic}</option>)}</select></label><label>Follow-up date<Input type="date" min="2026-09-25" value={draft.followUp} onChange={event => change({ followUp: event.target.value })} /><small>Leave blank if no follow-up is needed.</small></label><label>Recommendation<select aria-label="Recommendation" value={draft.recommendation} onChange={event => change({ recommendation: event.target.value })}>{['Pending review', 'Approve', 'Partially approve', 'Reject', 'Escalate'].map(value => <option key={value}>{value}</option>)}</select></label></div></fieldset>
    <fieldset><legend>Financial assessment · MYR</legend><div className="ws-form-grid"><label>Claimed amount<Input type="number" min="0" step="0.01" required value={draft.claimed} onChange={event => change({ claimed: event.target.value })} /></label><label>Eligible amount<Input type="number" min="0" step="0.01" required value={draft.eligible} onChange={event => change({ eligible: event.target.value })} /></label><label>Deductible<Input type="number" min="0" step="0.01" required value={draft.deductible} onChange={event => change({ deductible: event.target.value })} /></label><div className="ws-payable"><span>Provisional net payable</span><strong>{money(Math.max(0, Number(draft.eligible) - Number(draft.deductible)))}</strong><small>Eligible amount less deductible.</small></div></div></fieldset>
    <label className="ws-rationale">Assessment rationale<textarea rows={5} value={draft.rationale} onChange={event => change({ rationale: event.target.value })} placeholder="Record how the evidence meets the policy benefit, any exclusions, and your decision." required maxLength={4000} /></label>
    <div className="ws-form-footer"><Button variant="primary" type="submit" disabled={!dirty}>Save assessment</Button><Button onClick={reset} disabled={!dirty}>Discard changes</Button></div><p className="ws-local-caption">Saves a local preview assessment and adds an audit entry. No backend update.</p>
  </form></>
}

export function History({ state }: { state: WorkspaceState }) {
  return <><div className="ws-centre-heading"><div><h2>Activity history</h2><p>Complete audit trail · newest first · Malaysia time</p></div><Badge>{state.history.length} events</Badge></div><ol className="ws-history">{[...state.history].sort((a, b) => b.date.localeCompare(a.date)).map(event => <li key={event.id}><span className="ws-history-dot" /><div><div className="ws-history-title"><h3>{event.title}</h3><time dateTime={event.date}>{stamp(event.date)}</time></div><p>{event.detail}</p><small>{event.actor}</small></div></li>)}</ol></>
}
