import { useState } from 'react'
import { ArrowRight, Check, FolderSimple, Info, Layout, MagnifyingGlass, Plus, SquaresFour } from '@phosphor-icons/react'
import { Badge, Button, Card, Input, Panel, PreviewIcon, Table, Tabs } from './components/primitives'

export function FoundationPreview({ page }: { page: string }) {
  const [tab, setTab] = useState('controls')
  const [notice, setNotice] = useState('')
  return <>
    <div className="pv-page-heading"><div><div className="pv-eyebrow">INTERFACE FOUNDATION <span>/ 01</span></div><h1>{page}</h1><p>A shared foundation for your day-to-day claims work.</p></div><Badge><PreviewIcon icon={Layout} /> Shell preview</Badge></div>
    <Panel className="pv-placeholder" aria-label={`${page} placeholder`}>
      <div className="pv-placeholder-top"><span className="pv-eyebrow">{page.toUpperCase()}</span><span className="pv-placeholder-label"><span /> Content reserved</span></div>
      <div className="pv-placeholder-body"><div className="pv-placeholder-icon"><PreviewIcon icon={page === 'Workbasket' ? SquaresFour : FolderSimple} size="illustration" /></div><h2>Room for the work ahead.</h2><p>This is the {page.toLowerCase()} canvas.<br />For now, we’re reviewing the frame around it.</p><div className="pv-placeholder-note"><PreviewIcon icon={Info} /> Page content comes in the next stage</div></div>
      <div className="pv-placeholder-bottom"><span>Navigation, hierarchy, and surfaces</span><a href={page === 'Claim workspace' ? '/ui-preview/workbasket' : '/ui-preview/workspace'}>{page === 'Claim workspace' ? 'View Workbasket shell' : 'View workspace shell'}<PreviewIcon icon={ArrowRight} /></a></div>
    </Panel>
    <div className="pv-section-heading"><div><h2>Shared foundations</h2><p>A small specimen of the controls used across the preview.</p></div><span className="pv-mono pv-caption">FOUNDATION ONLY</span></div>
    <Panel className="pv-specimens" aria-label="Shared component specimens">
      <Tabs label="Foundation specimens" items={[{ id: 'controls', label: 'Controls' }, { id: 'type', label: 'Typography & spacing' }, { id: 'table', label: 'Table treatment' }]} value={tab} onChange={setTab}>
        {tab === 'controls' ? <div className="pv-specimen-grid"><div><h3 className="pv-eyebrow">ACTIONS</h3><div className="pv-control-row"><Button variant="primary" onClick={() => setNotice('Primary button selected. This is a visual specimen only.')}><PreviewIcon icon={Plus} />Primary action</Button><Button onClick={() => setNotice('Secondary button selected. This is a visual specimen only.')}>Secondary</Button><Button variant="ghost" onClick={() => setNotice('Text action selected. This is a visual specimen only.')}>Text action<PreviewIcon icon={ArrowRight} /></Button></div><p className="pv-specimen-feedback" role="status">{notice || 'Clear hierarchy. One primary action at a time.'}</p></div><div><h3 className="pv-eyebrow">INPUT & STATUS</h3><label className="pv-sr-only" htmlFor="preview-example-input">Example search input</label><div className="pv-example-input"><PreviewIcon icon={MagnifyingGlass} /><Input id="preview-example-input" placeholder="An example input…" /></div><div className="pv-control-row pv-badge-examples"><Badge>Neutral</Badge><Badge tone="accent">Needs attention</Badge><Badge tone="success"><PreviewIcon icon={Check} />Complete</Badge></div></div></div> : tab === 'type' ? <div className="pv-type-grid"><div><span className="pv-eyebrow">INTER / 400 · 500 · 600</span><p className="pv-type-display">Clarity at every level.</p><p className="pv-body">Readable body text for focused, everyday work.</p><p className="pv-caption pv-mono">JETBRAINS MONO · Metadata / 12px</p></div><Card><h3>Measured, consistent spacing</h3><dl className="pv-token-list"><div><dt>Sidebar / header</dt><dd>232 / 64px</dd></div><div><dt>Page inset / section gap</dt><dd>32 / 24px</dd></div><div><dt>Controls / table rows</dt><dd>36 / 44px</dd></div><div><dt>Panel / control radius</dt><dd>16 / 8px</dd></div></dl></Card></div> : <Table label="Design token table specimen"><thead><tr><th scope="col">Element</th><th scope="col">Purpose</th><th scope="col">Size</th><th scope="col">Treatment</th></tr></thead><tbody><tr><td>Navigation icon</td><td>Primary wayfinding</td><td className="pv-mono">20px</td><td><Badge>Regular</Badge></td></tr><tr><td>Control icon</td><td>Actions & inputs</td><td className="pv-mono">16px</td><td><Badge>Regular</Badge></td></tr><tr><td>Placeholder icon</td><td>Supporting illustration</td><td className="pv-mono">24px</td><td><Badge>Regular</Badge></td></tr></tbody></Table>}
      </Tabs>
    </Panel>
  </>
}
