/**
 * Extract email content from .msg files in sources/_email_staging
 * and write it to src/data/emailContents.ts
 *
 * Run: node scripts/extract-emails.mjs
 */
import fs from 'fs';
import path from 'path';
import MsgReader from 'msgreader';

const ROOT = process.cwd();
const EMAIL_DIR = path.join(ROOT, 'sources', '_email_staging');
const OUT_FILE = path.join(ROOT, 'src', 'data', 'emailContents.ts');

// Collect all folder IDs that have .msg files
const folderIds = fs.readdirSync(EMAIL_DIR).filter(d =>
  fs.statSync(path.join(EMAIL_DIR, d)).isDirectory()
);

const records = [];

for (const folderId of folderIds) {
  const folderPath = path.join(EMAIL_DIR, folderId);
  const files = fs.readdirSync(folderPath).filter(f => f.endsWith('.msg'));

  for (const file of files) {
    const filePath = path.join(folderPath, file);
    try {
      const msgFileBuffer = fs.readFileSync(filePath);
      const reader = new MsgReader.default
        ? new MsgReader.default(msgFileBuffer)
        : new MsgReader(msgFileBuffer);
      const msgData = reader.getFileData();

      const from = msgData.senderEmail || msgData.senderName || '';
      const to = (msgData.recipients || []).map(r => r.email || r.name).join('; ');
      const subject = msgData.subject || '';
      const body = (msgData.body || '').trim();
      const sentDate = msgData.messageDeliveryTime || msgData.clientSubmitTime || '';

      records.push({
        folderId,
        filename: file,
        from,
        to,
        subject,
        body: body.substring(0, 3000), // cap very long emails
        sentDate: sentDate ? new Date(sentDate).toISOString() : '',
      });
    } catch (err) {
      console.error(`Failed to parse ${filePath}: ${err.message}`);
      records.push({
        folderId,
        filename: file,
        from: '',
        to: '',
        subject: file.replace(/\.msg$/, ''),
        body: '[Could not parse .msg file]',
        sentDate: '',
      });
    }
  }
}

// Generate TypeScript output
const tsLines = [
  '// Auto-generated by scripts/extract-emails.mjs — do not edit manually.',
  `// Extracted ${records.length} emails from sources/_email_staging on ${new Date().toISOString().slice(0, 10)}.`,
  '',
  'export interface ExtractedEmail {',
  '  folderId: string;',
  '  filename: string;',
  '  from: string;',
  '  to: string;',
  '  subject: string;',
  '  body: string;',
  '  sentDate: string;',
  '}',
  '',
  'export const extractedEmails: ExtractedEmail[] = ' + JSON.stringify(records, null, 2) + ';',
  '',
  '/** Look up extracted email by folder ID */',
  'export function getEmailByFolder(folderId: string): ExtractedEmail | undefined {',
  '  return extractedEmails.find(e => e.folderId === folderId);',
  '}',
  '',
];

fs.writeFileSync(OUT_FILE, tsLines.join('\n'), 'utf-8');
console.log(`Wrote ${records.length} email records to ${OUT_FILE}`);
